# Site settings
title: Gitparade
email: peter@forret.com
description: > # this means to ignore newlines until "baseurl:"
  GitParade package managers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: pforret
github_username: gitparade-com

# Build settings
markdown: kramdown
