# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gitparade - Package repositories
email: peter@forret.com
description: > # this means to ignore newlines until "baseurl:"
  GitParade mùain website
baseurl: "/www.gitparade.com" # the subpath of your site, e.g. /blog
url: "https://gitparade-com.github.io" # the base hostname & protocol for your site
twitter_username: pforret
github_username:  gitparade-com

# Build settings
markdown: kramdown
theme: minima
