# Site settings
title: Gitparade
email: peter@forret.com
description: > # this means to ignore newlines until "baseurl:"
  GitParade package managers
baseurl: "/www.gitparade.com" 
url: "https://gitparade-com.github.io" 

twitter_username: pforret
github_username: gitparade-com

# Build settings
markdown: kramdown
